### ISSUE TITLE
Evaluate alternative NoSQL database backends

### ISSUE THREAD

**Issue by jeancochrane** [azavea/ashlar-2018-fellowship#13]
Postgres is Ashlar's heaviest dependency, and a barrier to simple deployment. It would be nice to allow alternative NoSQL database backends that wouldn't require so much configuration. This will involve some research to determine an appropriate library/service, since the database needs to be:

- Easy to configure and deploy
- Support simple filtering/querying
- Either free or cheap

**Comment by jeancochrane** [comment]
I spent some time researching possible NoSQL backends, as outlined in this ADR: https://github.com/azavea/grout-2018-fellowship/blob/master/docs/nosql-backends.md

The gist of my findings:

1. The field has expanded since 2015, and there are a number of popular, scalable NoSQL backends and providers
2. MongoDB is the only backend that currently meets all of the basic requirements for a Grout backend (the primary blocker is geospatial querying, which isn't widely supported in NoSQL database managers) 
3. No backend or provider is currently substantially cheaper or easier to deploy than Postgres

Based on these findings, we agreed that this chunk of work wasn't yet a good enough value proposition for the project to warrant spending fellowship time. We should revisit this issue in six months to a year and see if the field has changed.

**Comment by jeancochrane** [comment]
Recap for @ddohler and @flibbertigibbet: Today after the TSM I had a great convo with @jfrankl about pure-JS implementations of Grout. Jeff asked whether we had considered using [Turf](http://turfjs.org/) for geospatial querying and as I was explaining why I didn't think it would work I realized that I wasn't actually so sure -- in particular it seems plausible to me that we could store the entire database as one GeoJSON FeatureCollection and use Turf for the geospatial queries, which would get us closer to being able to use a JSON-store-as-a-service like [JSONBin](https://jsonbin.io/) for the database. We'd still need a server to run the Turf querying logic, but it would allow us to simplify the database layer a bit (although it might be interesting to try using a serverless approach with e.g. Lambda for the Turf queries).

I haven't thought this through very carefully so it'll need some more detailed evaluation, but this seems like an interesting line of inquiry to pursue the next time we revisit the dream of managed NoSQL backends.

**Comment by jfrankl** [comment]
For spatial queries on the frontend, I've had success pairing [RBush](https://github.com/mourner/rbush) with [Turf](http://turfjs.org/). RBush does an initial spatial query; it's very fast but limited to searching for points and rectangles within a bounding box. Then I'll use Turf to query the features that were filtered by RBush.

I don't have any insight into how this could be useful for Grout.

**Comment by ddohler** [comment]
This is a really interesting idea! It's a good reminder that just because a particular storage backend does not offer all the querying possibilities that Postgres does, that doesn't mean that we can't replace what's missing using other technology -- it may still be fast enough to be useful.

I think that there are a few different ways that this could go.

One might be to have a server that runs in front of the database and provides a unified interface to client-side Javascript. Depending on the database being used, the server could emulate certain types of filtering at the application level if they're not natively supported by the database. Then the client-side Javascript could always rely on the API being the same, no matter what database was being used. My immediate reaction is that this would be a pretty significant increase in the complexity of the Grout stack, which would reduce one of the benefits of using a non-Postgres database, namely that it is easier to set up and maintain.

Another approach, which I think would be closer to what @jfrankl is getting at, would be to push that complexity forward into the client-side Javascript, and run Turf in the browser. Then, if the database doesn't support spatial filtering, the Grout Javascript API would query the database with whatever filters it does support, and then use Turf and/or RBush to further filter down the results after receiving a response from the server. The downside to this is that the client-side app would end up loading (potentially many) more records than it needs and then doing the filtering in-browser, which could make the app feel slow. I think that whether this type of architecture would work well might be application-specific; if the usage patterns are such that the user can load up a big batch of records at the start and then experiment with different spatial filters on them, then that would probably work best. On the other hand, if the user is frequently changing non-geospatial filters and reloading from the API, then the frontend will have to keep rebuilding its RBush index on each new API response, which will cause things slow down.

**Comment by flibbertigibbet** [comment]
The geospatial query support for the NoSQL backends Firebase and DynamoDB both involve geohashing to support server-side geospatial filtering, including from "serverless" functions. MongoDB uses the newer C++ implementation of the S2 library, according to [this](https://www.mongodb.com/blog/post/new-geo-features-in-mongodb-24); DynamoDB uses the older Java [S2](http://s2geometry.io/) implementation.

For a small enough data set, as @ddohler and @jfrankl have pointed out, the filtering could be done entirely client-side, in which case I would see no reason to use `grout` for such a project, as its primary functionality is in server-side storage and filtering for potentially large data sets. Other libraries would suffice for filtering and JSON schema validation in an implementation that holds all data in memory on the client.
